version: '3'

services:
  mongo:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - ./data:/data/db
    networks:
      - fastapi-mongo
  fastapi:
    build: .
    image: fastapi-mongo
    environment:
      PORT: 5000
      MONGO_URL: mongodb://mongo:27017
      MONGO_DB: fastapi
    ports:
      - 5000:5000
    networks:
      - fastapi-mongo
    depends_on:
      - mongo

networks:
  fastapi-mongo:
    driver: bridge

